# Generated by Django 4.1.5 on 2023-01-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_admin_for_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sign_Up',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('Sign_Up_date', models.DateTimeField()),
                ('gender', models.BooleanField()),
                ('accessForAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Type_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_missing_item', models.TextField()),
                ('image', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('contact_number', models.IntegerField()),
                ('post_detail', models.TextField()),
                ('uploaded_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
                ('Aprovement_Not', models.BooleanField()),
                ('active', models.IntegerField()),
                ('access_admin_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.access_admin_for_users')),
                ('auther_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.sign_up')),
                ('type_item_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.type_item')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField()),
                ('Sign_Up_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.sign_up')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_date_time', models.DateTimeField()),
                ('message_topic', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('user_name_id_sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.sign_up')),
            ],
        ),
        migrations.CreateModel(
            name='Autherized_post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.post')),
                ('user_name_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.sign_up')),
            ],
        ),
        migrations.AddField(
            model_name='access_admin_for_users',
            name='user_name_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.sign_up'),
        ),
    ]
