# Generated by Django 3.2.10 on 2023-01-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Date', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('By_user', models.TextField()),
                ('chat_count', models.IntegerField()),
                ('Action', models.TextField()),
                ('date_of_edit', models.DateField(default='1-1-1950')),
            ],
        ),
        migrations.CreateModel(
            name='Sign_Up',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('Sign_Up_date', models.DateTimeField()),
                ('gender', models.BooleanField()),
                ('accessForAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField()),
                ('Sign_Up_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.sign_up')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_date_time', models.DateTimeField()),
                ('message_topic', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('user_name_id_sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.sign_up')),
            ],
        ),
        migrations.CreateModel(
            name='Autherized_post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.post')),
                ('user_name_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.sign_up')),
            ],
        ),
        migrations.CreateModel(
            name='Access_admin_for_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafqodat.sign_up')),
            ],
        ),
    ]
