# Generated by Django 3.2.10 on 2023-01-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafqodat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_of_edit',
        ),
    ]
