# Generated by Django 3.2.10 on 2023-01-16 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mafqodat', '0002_remove_post_date_of_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='Sign_Up_date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
